version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: beaconred-quiz-postgresql
    ports:
      - "5432:5432"
    volumes:
      - ./.data/db:/var/lib/postgresql/data
      - ./server/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file: postgres.env
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}" ]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - beaconred-quiz-intranet

  server:
    build:
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - beaconred-quiz-intranet

  client:
    build:
      context: ./client
      args:
        VITE_SERVER_URL: http://localhost:3001
    ports:
      - "4173:80"
    depends_on:
      - server
    networks:
      - beaconred-quiz-intranet

networks:
  beaconred-quiz-intranet:
    driver: bridge