version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: beaconred-quiz-postgresql
    ports:
      - "5432:5432"
    volumes:
      - ./.data/db:/var/lib/postgresql/data
      - ./server/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file: postgres.env
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - beaconred-quiz-intranet

networks:
  beaconred-quiz-intranet:
    driver: bridge